Added github action for black
awslabs/terraform-iam-policy-validator pull request #26
Opened 2023-12-22 15:30 UTC by cibinmathew

Added github action hook for [black](https://github.com/psf/black) formatter
*Issue #11,

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-26 16:04 UTC, ninaw3 requested changes
Thanks for your contribution! Can you resolve merge conflicts? Thanks!

2024-07-17 20:53 UTC, cibinmathew commented
@ninaw3 pls check now

2024-07-18 20:34 UTC, mponaws approved these changes

2024-07-18 20:35 UTC, mponaws commented
Thank you for your contribution @cibinmathew ! Merging the changes.

2024-07-18 20:35 UTC, merged